services:
  - type: web
    name: search-engine-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://searchengine-h77b.onrender.com/api
      - key: VITE_FRONTEND_REPO_URL
        value: https://github.com/yourusername/search_engine_fe
      - key: VITE_BACKEND_REPO_URL
        value: https://github.com/yourusername/search_engine_be
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
